server:
  port: 8555
# 路由映射
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    movie-service:
      path: /movie/**
      serviceId: movie-service
  retryable: true
user-service:
  ribbon:
    okToRetryOnAllOperations: true
    maxAutoRetiesNextServer: 3
    maxAutoRetries: 3

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://krista.service.registry.B:18765/eureka/,http://krista.service.registry.A:8765/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  rabbitmq:
    host: rabbitmq.krista.com
    port: 5672
    username: krista
    password: krista008
    virtual-host: zipkin
  application:
    name: zuul-gateway
  sleuth:
    sampler:
      percentage: 1.0