# mybatis
mybatis:
  # 实体模型所在包路径
  type-aliases-package: com.krista.spring.boot.mybatis.model
  # mapper对应的xml文件
  mapper-locations: classpath*:mapper/**/*.xml

# 分页插件
pagehelper:
  # 支持的数据库：mysql
  helper-dialect: mysql

# 通用mapper
mapper:
  # mapper基接口，该类不能被扫描到
  # mappers: com.krista.spring.boot.base.MyMapper
  not-empty: true
  identity: MYSQL

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.krista.com:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 1q2w#E$R
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.krista.spring.boot.mybatis.dao: debug