eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://krista.service.registry.B:18765/eureka/,http://krista.service.registry.A:8765/eureka/
server:
  port: 9494
spring:
  rabbitmq:
    host: rabbitmq.krista.com
    port: 5672
    username: krista
    password: krista008
    virtual-host: zipkin
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://mysql.krista.com:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1q2w#E$R
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql