spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://www.baidu.com
        predicates:
        - Path=/baidu/**
        # - RemoteAddr=192.168.1.1/24
        filters:
        - StripPrefix=1
      - id: test
        uri: http://127.0.0.1:7071
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
            key-resolver: "#{@pathKeyResolver}"
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 7070
# 启动监控端点
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","gateway"]
