debug: false
eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://krista.service.registry.B:18765/eureka/,http://krista.service.registry.A:8765/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${server.port}

# 关闭默认favicon
# spring.mvc.favicon.enabled=true
server:
  port: 8000

security:
  basic:
    enabled: false
  user:
    name: krista
    password: krista008
management:
  security:
    enabled: true
    role: ADMIN

# 开启/shutdown,默认false
endpoints:
  shutdown:
    enabled: false

# 定义系统的info信息
info:
  application:
    name: springboot-1.x-test
    desc: aaaa
    version: V0.1
  author:
    name: krista
    email: 1366678737@qq.com
    url: https://github.com/wdhxwz

# database
spring:
  rabbitmq:
    host: rabbitmq.krista.com
    port: 5672
    username: krista
    password: krista008
    virtual-host: zipkin
  application:
    name: user-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  zipkin:
    base-url: http://127.0.0.1:9494
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    root: info
    org:
      hibernate: info
      hibernate.type.descriptor.sql.BasicBinder: trace
      hibernate.type.descriptor.sql.BasicExtractor: trace