debug: false
eureka:
  client:
    health-check:
      enabled: false
    service-url:
      defaultZone: http://krista.service.registry.B:18765/eureka/,http://krista.service.registry.A:8765/eureka/
  instance:
    metadata-map:
      user:
        name: krista
        password: krista008
    prefer-ip-address: true
    status-page-url-path: /swagger-ui.html
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #instance-id: ${spring.application.name}:${server.port}

# 关闭默认favicon
# spring.mvc.favicon.enabled=true
server:
  port: 8000

security:
  basic:
    enabled: false
  user:
    name: krista
    password: krista008
management:
  security:
    enabled: false

# 开启/shutdown,默认false
endpoints:
  shutdown:
    enabled: false
  health:
    enabled: true
  enabled: false

# 定义系统的info信息
info:
  application:
    name: springboot-1.x-test
    desc: aaaa
    version: V0.1
  author:
    name: krista
    email: 1366678737@qq.com
    url: https://github.com/wdhxwz

# 该配置不是必须的
swagger2:
  applicationName: springboot-1.x-test
  description: aaaa
  version: V0.1
  userName: krista
  url: https://github.com/wdhxwz
  email: 1366678737@qq.com


# database
spring:
  http:
    log-request-details: true
    encoding:
      charset: utf-8
      force: true
      enabled: true
  rabbitmq:
    host: rabbitmq.krista.com
    port: 5672
    username: krista
    password: krista008
    virtual-host: zipkin
  application:
    name: user-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    root: info
    org:
      hibernate: info
      hibernate.type.descriptor.sql.BasicBinder: trace
      hibernate.type.descriptor.sql.BasicExtractor: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%-5level ----[%class:%line] - %msg%n"